builds:
  - id: miaospeed
    dir: .
    binary: miaospeed
    ldflags:
      - -s -w -X "main.COMMIT={{.Commit}}" -X "main.BUILDCOUNT={{2}}" -X "main.BRAND={{Miaospeed}}" -X "main.COMPILATIONTIME={{.Env.COMPILATIONTIME}}"
    goos:
      - darwin
      - linux
      - windows
archives:
  - files:
      - README.md
